package com.acts.auth

enum class AdminAuditLogAction {
    LOGIN_SUCCESS,
    USER_ASSIGNMENT_UPDATED,
    VIEWER_ALLOWLIST_ADDED,
    VIEWER_ALLOWLIST_REMOVED,
    ASSET_ACCESS_DENIED,
    ASSET_ACCESS_SCOPE_UPDATED,
    ASSET_EXPORTED,
    ASSET_RETENTION_POLICY_UPDATED,
    ASSET_RESTORED,
}
