insert into user_accounts (
    email,
    display_name,
    organization_id,
    role,
    mapping_mode,
    company_wide_viewer
)
values
    ('sykim@iportfolio.co.kr', '김성윤', null, 'ADMIN', 'UNMAPPED', true),
    ('jlee@iportfolio.co.kr', '이종환', null, 'ADMIN', 'UNMAPPED', true),
    ('jelee@iportfolio.co.kr', '이지은', null, 'USER', 'UNMAPPED', false),
    ('hlee@iportfolio.co.kr', '이한성', null, 'USER', 'UNMAPPED', false),
    ('dssong@iportfolio.co.kr', '송다슬', null, 'USER', 'UNMAPPED', false),
    ('jinapark@iportfolio.co.kr', '박지나', null, 'USER', 'UNMAPPED', false),
    ('cyheo@iportfolio.co.kr', '허채영', null, 'USER', 'UNMAPPED', false),
    ('ghnoh@iportfolio.co.kr', '노광훈', null, 'USER', 'UNMAPPED', false),
    ('jpark@iportfolio.co.kr', '박지호', null, 'USER', 'UNMAPPED', false),
    ('akang@iportfolio.co.kr', '강아름', null, 'USER', 'UNMAPPED', false),
    ('sjkim@iportfolio.co.kr', '김성준', null, 'USER', 'UNMAPPED', false),
    ('hrkim@iportfolio.co.kr', '김해린', null, 'USER', 'UNMAPPED', false),
    ('sypark@iportfolio.co.kr', '박소연', null, 'USER', 'UNMAPPED', false),
    ('seolalee@iportfolio.co.kr', '이설아', null, 'USER', 'UNMAPPED', false),
    ('hjyoun@iportfolio.co.kr', '윤현주', null, 'USER', 'UNMAPPED', false),
    ('hhong@iportfolio.co.kr', '홍효송', null, 'USER', 'UNMAPPED', false),
    ('jwkim@iportfolio.co.kr', '김정우', null, 'USER', 'UNMAPPED', false),
    ('gjang@iportfolio.co.kr', '장경화', null, 'USER', 'UNMAPPED', false),
    ('ejyoo@iportfolio.co.kr', '유은지', null, 'USER', 'UNMAPPED', false),
    ('shkang@iportfolio.co.kr', '강서희', null, 'USER', 'UNMAPPED', false),
    ('jymoon@iportfolio.co.kr', '문지윤', null, 'USER', 'UNMAPPED', false),
    ('rykwon@iportfolio.co.kr', '권라윤', null, 'USER', 'UNMAPPED', false),
    ('isjang@iportfolio.co.kr', '장인선', null, 'USER', 'UNMAPPED', false),
    ('yjchae@iportfolio.co.kr', '채영지', null, 'USER', 'UNMAPPED', false),
    ('chlee@iportfolio.co.kr', '이창환', null, 'USER', 'UNMAPPED', false),
    ('hkim@iportfolio.co.kr', '김희진', null, 'USER', 'UNMAPPED', false),
    ('jrlee@iportfolio.co.kr', '이장록', null, 'USER', 'UNMAPPED', false),
    ('jejun@iportfolio.co.kr', '전지은', null, 'USER', 'UNMAPPED', false),
    ('shkim@iportfolio.co.kr', '김수환', null, 'USER', 'UNMAPPED', false),
    ('kmcha@iportfolio.co.kr', '차경민', null, 'USER', 'UNMAPPED', false),
    ('shlee@iportfolio.co.kr', '이수한', null, 'USER', 'UNMAPPED', false),
    ('dslee@iportfolio.co.kr', '이다성', null, 'USER', 'UNMAPPED', false),
    ('sseo@iportfolio.co.kr', '서성운', null, 'USER', 'UNMAPPED', false),
    ('ykwak@iportfolio.co.kr', '곽윤설', null, 'USER', 'UNMAPPED', false),
    ('jaehwankim@iportfolio.co.kr', '김재환', null, 'USER', 'UNMAPPED', false),
    ('jiwookim@iportfolio.co.kr', '김지우', null, 'USER', 'UNMAPPED', false),
    ('hshin@iportfolio.co.kr', '신휘재', null, 'USER', 'UNMAPPED', false),
    ('hjjun@iportfolio.co.kr', '전혜주', null, 'USER', 'UNMAPPED', false),
    ('mhkim@iportfolio.co.kr', '김민형', null, 'USER', 'UNMAPPED', false),
    ('yjkang@iportfolio.co.kr', '강연주', null, 'USER', 'UNMAPPED', false),
    ('ghwang@iportfolio.co.kr', '황기홍', null, 'USER', 'UNMAPPED', false),
    ('yhcho@iportfolio.co.kr', '조용환', null, 'USER', 'UNMAPPED', false),
    ('seokhyeonkim@iportfolio.co.kr', '김석현', null, 'USER', 'UNMAPPED', false),
    ('minsungkim@iportfolio.co.kr', '김민성', null, 'USER', 'UNMAPPED', false),
    ('bson@iportfolio.co.kr', '손병성', null, 'ADMIN', 'UNMAPPED', true),
    ('ischoi@iportfolio.co.kr', '최인수', null, 'USER', 'UNMAPPED', false),
    ('jaehyunlee@iportfolio.co.kr', '이재현', null, 'USER', 'UNMAPPED', false),
    ('sbyoon@iportfolio.co.kr', '윤수빈', null, 'ADMIN', 'UNMAPPED', true),
    ('mkim@iportfolio.co.kr', '김미영', null, 'USER', 'UNMAPPED', false),
    ('hskwak@iportfolio.co.kr', '곽형선', null, 'USER', 'UNMAPPED', false),
    ('sshin@iportfolio.co.kr', '신소현', null, 'USER', 'UNMAPPED', false),
    ('mhhwang@iportfolio.co.kr', '황명현', null, 'USER', 'UNMAPPED', false),
    ('hshong@iportfolio.co.kr', '홍혜상', null, 'USER', 'UNMAPPED', false),
    ('hypark@iportfolio.co.kr', '박혜연', null, 'USER', 'UNMAPPED', false),
    ('sbpark@iportfolio.co.kr', '박수빈', null, 'USER', 'UNMAPPED', false),
    ('bettylee@iportfolio.co.kr', '이보람(betty)', null, 'USER', 'UNMAPPED', false),
    ('ywkim@iportfolio.co.kr', '김예원', null, 'USER', 'UNMAPPED', false),
    ('yhyun@iportfolio.co.kr', '윤연호', null, 'USER', 'UNMAPPED', false),
    ('blee@iportfolio.co.kr', '이보람', null, 'USER', 'UNMAPPED', false),
    ('dwjung@iportfolio.co.kr', '정다원', null, 'USER', 'UNMAPPED', false),
    ('cykim@iportfolio.co.kr', '김채영', null, 'USER', 'UNMAPPED', false),
    ('hongjinkim@iportfolio.co.kr', '김홍진', null, 'USER', 'UNMAPPED', false),
    ('ghcheon@iportfolio.co.kr', '천광호', null, 'USER', 'UNMAPPED', false),
    ('sychoi@iportfolio.co.kr', '최수용', null, 'USER', 'UNMAPPED', false),
    ('helim@iportfolio.co.kr', '임하은', null, 'USER', 'UNMAPPED', false),
    ('eko@iportfolio.co.kr', '고은희', null, 'USER', 'UNMAPPED', false),
    ('hyojeongkim@iportfolio.co.kr', '김효정', null, 'USER', 'UNMAPPED', false),
    ('hblee@iportfolio.co.kr', '이한비', null, 'USER', 'UNMAPPED', false),
    ('hyejikim@iportfolio.co.kr', '김혜지', null, 'USER', 'UNMAPPED', false),
    ('bspark@iportfolio.co.kr', '박범석', null, 'USER', 'UNMAPPED', false),
    ('hcho@iportfolio.co.kr', '조하담', null, 'USER', 'UNMAPPED', false),
    ('cyyoon@iportfolio.co.kr', '윤찬유', null, 'USER', 'UNMAPPED', false)
on conflict (email) do update
set display_name = excluded.display_name,
    role = excluded.role,
    company_wide_viewer = case
        when excluded.role = 'ADMIN' then true
        else user_accounts.company_wide_viewer
    end,
    updated_at = current_timestamp;
