create table departments (
    id bigint generated by default as identity primary key,
    name varchar(120) not null unique,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table user_accounts (
    email varchar(255) primary key,
    display_name varchar(120) not null,
    department_id bigint references departments(id),
    position_title varchar(120),
    role varchar(32) not null,
    mapping_mode varchar(32) not null,
    company_wide_viewer boolean not null default false,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    last_login_at timestamp
);

-- Department bootstrap is managed outside this repository.
