alter table user_accounts rename column department_id to team_id;
alter table user_accounts drop constraint if exists user_accounts_department_id_fkey;

alter table departments rename to teams;

create table departments (
    id bigint generated by default as identity primary key,
    name varchar(120) not null unique,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

insert into departments (name) values
    ('전략본부'),
    ('콘텐츠개발본부'),
    ('디자인본부'),
    ('경영지원본부'),
    ('영상본부'),
    ('마케팅본부');

alter table teams add column department_id bigint;

update teams
set department_id = (select id from departments where name = '전략본부')
where name = 'AI전략사업팀';

update teams
set department_id = (select id from departments where name = '콘텐츠개발본부')
where name in ('콘텐츠개발1팀', '콘텐츠개발2팀');

update teams
set department_id = (select id from departments where name = '디자인본부')
where name = '디자인팀';

update teams
set department_id = (select id from departments where name = '경영지원본부')
where name = '경영지원팀';

update teams
set department_id = (select id from departments where name = '영상본부')
where name = '영상팀';

update teams
set department_id = (select id from departments where name = '마케팅본부')
where name = '마케팅팀';

alter table teams alter column department_id set not null;
alter table teams add constraint teams_department_id_fkey foreign key (department_id) references departments(id);

alter table user_accounts add column department_id bigint;

update user_accounts ua
set department_id = t.department_id
from teams t
where ua.team_id = t.id;

alter table user_accounts add constraint user_accounts_team_id_fkey foreign key (team_id) references teams(id);
alter table user_accounts add constraint user_accounts_department_id_fkey foreign key (department_id) references departments(id);

create table viewer_allowlist (
    email varchar(255) primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table admin_audit_logs (
    id bigint generated by default as identity primary key,
    actor_email varchar(255) not null,
    action_type varchar(64) not null,
    target_email varchar(255) not null,
    before_state text,
    after_state text,
    created_at timestamp not null default current_timestamp
);
