alter table user_accounts rename column department_id to team_id;
alter table user_accounts drop constraint if exists user_accounts_department_id_fkey;

alter table departments rename to teams;

create table departments (
    id bigint generated by default as identity primary key,
    name varchar(120) not null unique,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

alter table teams add column department_id bigint;

alter table teams alter column department_id set not null;
alter table teams add constraint teams_department_id_fkey foreign key (department_id) references departments(id);

alter table user_accounts add column department_id bigint;

update user_accounts ua
set department_id = t.department_id
from teams t
where ua.team_id = t.id;

-- Department and team bootstrap is managed outside this repository.

alter table user_accounts add constraint user_accounts_team_id_fkey foreign key (team_id) references teams(id);
alter table user_accounts add constraint user_accounts_department_id_fkey foreign key (department_id) references departments(id);

create table viewer_allowlist (
    email varchar(255) primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create table admin_audit_logs (
    id bigint generated by default as identity primary key,
    actor_email varchar(255) not null,
    action_type varchar(64) not null,
    target_email varchar(255) not null,
    before_state text,
    after_state text,
    created_at timestamp not null default current_timestamp
);
