spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: ${SERVER_PORT:8088}
  forward-headers-strategy: native

acts:
  auth:
    backend-base-url: ${BACKEND_BASE_URL}
    frontend-base-url: ${FRONTEND_BASE_URL}
  storage:
    bucket: acts-assets-prod
  preview:
    video-thumbnail-lambda-function-name: ${ACTS_PREVIEW_VIDEO_THUMBNAIL_LAMBDA_FUNCTION_NAME:acts-video-preview-generator}
