spring:
  application:
    name: acts-backend
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

acts:
  auth:
    allowed-domain: iportfolio.co.kr
    admin-emails:
      - minsungkim@iportfolio.co.kr
  storage:
    region: ap-northeast-2
