spring:
  application:
    name: acts-backend
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

acts:
  auth:
    allowed-domains:
      - iportfolio.co.kr
      - spindlebooks.com
  storage:
    region: ap-northeast-2
